### ISSUE TITLE
Current project status?

### ISSUE THREAD

**Issue by proffalken** [holoplot/radioauth#3]
Hello,

This would be really handy for us to integrate our Hackspace membership platform with our WiFi networks so members get a better QoS than guests.

I'm wondering how frequently this is maintained and whether it is still actively used before I investigate further?

Thanks in advance!

**Comment by zonque** [comment]
We are no longer using this tool internally, but it worked well until we changed our auth scheme.

Hence there won't be any active contributions from our side, but PRs are always welcome of course.

**Comment by proffalken** [comment]
Thanks, appreciate the quick response.

I'm not a Go developer unfortunately, so I'll what my other options are and come back to this if I don't have any luck elsewhere.
